### ISSUE TITLE
Dependencies in conflict

### ISSUE THREAD

**Issue by micmarty** [xl-sr/CAL#13]
```bash
$ conda env create -f requirements.yml
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - mkl==2019.0=118
  - mkl_random==1.0.1=py27h4414c95_1 -> mkl[version='>=2018.0.3,<2019.0a0']
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ashwinbhy** [comment]
try using anaconda2 , it worked for me.

~/anaconda2/bin/conda env create -f requirements.yml

And to activate the same..
source activate ~/anaconda2/envs/CAL 

I also faced the same issue where i had anaconda3 installed , i tried to replicated the steps given in readme

**Comment by NuriBenbarka** [comment]
hi micmarty
in the requirements.yml file 
change the line 
-mki==2019.0=118 
to
-mki==2018.0.3=1
it worked for me after this change

**Comment by Elahe96** [comment]
I'm facing a problem making the environment any idea why I can't find packages?
conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - zlib==1.2.11=ha838bed_2
  - tk==8.6.8=hbc83047_0
  - tensorflow-base==1.10.0=gpu_py27had579c0_0
  - bcolz==1.2.1=py27h04863e7_0
  - readline==7.0=h7b6447c_5
  - yaml==0.1.7=had09818_2
  - protobuf==3.6.0=py27hf484d3e_0
  - jpeg==8d=2
  - blosc==1.14.4=hdbcaa40_0
  - numpy-base==1.15.1=py27h81de0dd_0
  - singledispatch==3.4.0.3=py27_0
  - locket==0.2.0=py27_1
  - lcms==1.19=0
  - cudatoolkit==9.2=0
  - hdf5==1.10.2=hba1933b_1
  - partd==0.3.8=py27_0
  - h5py==2.8.0=py27h989c5e5_3
  - pyyaml==3.13=py27h14c3975_0
  - mkl_random==1.0.1=py27h4414c95_1
  - numpy==1.15.1=py27h1d66e8a_0
  - markupsafe==1.0=py27h14c3975_1
  - ncurses==6.1=hf484d3e_0
  - tblib==1.3.2=py27_0
  - cytoolz==0.9.0.1=py27h14c3975_1
  - sqlite==3.24.0=h84994c4_0
  - libffi==3.2.1=hd88cf55_4
  - pandas==0.23.4=py27h04863e7_0
  - python==2.7.15=h1571d57_0
  - keras-preprocessing==1.0.2=py27_1
  - bzip2==1.0.6=h14c3975_5
  - tensorflow==1.10.0=gpu_py27h67ad7fe_0
  - pil==1.1.7=py27_2
  - mock==2.0.0=py27_0
  - pytables==3.4.4=py27ha205bf6_0
  - funcsigs==1.0.2=py27_0
  - tornado==5.1=py27h14c3975_0
  - mkl_fft==1.0.4=py27h4414c95_1
  - numexpr==2.6.8=py27hd89afb7_0
  - scipy==1.1.0=py27hfa4b5c9_1
  - openssl==1.0.2p=h14c3975_0
  - click==6.7=py27_0
  - libedit==3.1.20170329=h6b74fdf_2
  - keras-applications==1.0.4=py27_1
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libgcc-ng==8.2.0=hdf63c60_1
  - freetype==2.5.5=2
  - tensorboard==1.10.0=py27hf484d3e_0
  - keras-base==2.2.2=py27_0
  - lzo==2.10=h49e0be7_2
  - snappy==1.1.7=hbae5bb6_3
  - backports_abc==0.5=py27_0
  - cupti==9.2.148=0
  - libpng==1.6.34=hb9fc6fc_0
  - msgpack-python==0.5.6=py27h6bb024c_1
  - psutil==5.4.7=py27h14c3975_0
  - cudnn==7.2.1=cuda9.2_0
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - grpcio==1.12.1=py27hdbcaa40_0
  - libprotobuf==3.6.0=hdbcaa40_0
