### ISSUE TITLE
data sems miss

### ISSUE THREAD

**Issue by zlw21gxy** [xl-sr/CAL#16]
thanks for your great work, when I try to download data, it seems loss
![image](https://user-images.githubusercontent.com/46110602/58780150-aa82bb00-860a-11e9-98a4-acc66142ce29.png)
may I ask why?

**Comment by xl-sr** [comment]
you can use either the download script or this link: 
https://drive.google.com/uc?id=1mIi83YjB-0Mfole8W6lSuJRrcy1zauSV

**Comment by zlw21gxy** [comment]
Thanks, I am appreciate for your great job, hope you will have more results
come up soon, I will keep following
