### ISSUE TITLE
command line for reproducing experiments in Table 1

### ISSUE THREAD

**Issue by robotsoft** [xl-sr/CAL#2]
Hello,

Could you let me know the command line for reproducing experiments in Table 1 in the paper? I wonder how to reproduce the experiment with MP, CIL, RL and CAL.

**Comment by xl-sr** [comment]
You can run the experiments for CAL if you follow the description in the readme.
For CIL checkout this [repo](https://github.com/carla-simulator/imitation-learning). For RL this [repo](https://github.com/carla-simulator/reinforcement-learning).
MP is not available on github to my knowledge (the values from the table are from the original CARLA paper).
