### ISSUE TITLE
No registered kernels

### ISSUE THREAD

**Issue by robotsoft** [xl-sr/CAL#4]
When I tried to run `driving_benchmark.py`, I encountered the following error.

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: cu_dnngru_6/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=87654321, seed2=0](cu_dnngru_6/transpose, cu_dnngru_6/ExpandDims_1, cu_dnngru_6/Const_1, cu_dnngru_6/concat)]]
```

**Comment by xl-sr** [comment]
Did you run setup.sh and enable the CAL environment?
The code requires tensorflow-gpu to run.

**Comment by robotsoft** [comment]
Thank you for pointing at tensorflow-gpu. My tensorflow-gpu installation was not properly configured. I fix it.

**Comment by chandan-angadi** [comment]
Hi @xl-sr  I have installed tensorflow==1.14 and tensorflow-gpu also but still i am facing this issue could  you please help?



tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnngru_1/CudnnRNN (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) with these attrs: [seed=87654321, dropout=0, input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="gru", seed2=0, is_training=true]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[cu_dnngru_1/CudnnRNN]]
Errors may have originated from an input operation.
Input Source operations connected to node cu_dnngru_1/CudnnRNN:
 cu_dnngru_1/transpose (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:271)	
 cu_dnngru_1/ExpandDims_1 (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:273)	
 cu_dnngru_1/concat (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:60)
