### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by robotsoft** [xl-sr/CAL#5]
When I tried to run `python driving_benchmark.py -c Town01 -v -n test`, I encountered the following error.

`ValueError: Shape must be rank 1 but is rank 4 for 'Batchnorm_0/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,6,13,512], [1,6,1,1], [1,6,1,1], [1,6,1,1], [1,6,1,1].`

**Comment by chowkamlee81** [comment]
@xl-sr 
Iam also getting the same error. Kindly let us know how you solved it.
@robotsoft 
Any progress so far in solving the problem
