### ISSUE TITLE
Could not find the model-weights in Google Drive

### ISSUE THREAD

**Issue by Deepak3994** [xl-sr/CAL#6]
Hi,

I was trying to run download-binaries-and-models.sh file. It trowed me an error while downloading the model weights.
To cross check, I opened the link and saw there was no file present infact it trowed an exception File Not Found.

**# download the model weights
gdown https://drive.google.com/uc\?id=1mIi83YjB-0Mfole8W6lSuJRrcy1zauSV**

**Comment by xl-sr** [comment]
The script works for me, must be a problem with your connection.
The link to download it in your browser is: 
https://drive.google.com/open?id=1mIi83YjB-0Mfole8W6lSuJRrcy1zauSV
